-- SELECT * FROM MANAGER;
-- SELECT * FROM CAR;
-- SELECT * FROM MODEL;
-- SELECT * FROM ADDRESS;
-- SELECT * FROM DRIVER;
SELECT * FROM DRIVE;
-- SELECT * FROM CLIENT;
-- SELECT * FROM LIVE;
-- SELECT * FROM RENT;




